import Head from "next/head";
import Dropdown from "./Dropdown";
import { useState } from "react";
import Link from "next/link";
import BarChart from "./new";

var userDetailsValue ={}
export default function Home() {
  const [userDetails, setuserDetails] = useState({
    interest: [], counter: " ", price_check: " ",
  });

  const [companyName, setCompanyName] = useState(" ");

  const onSelect = async (values) => {
    setuserDetails({ ...userDetails, interest: values })
  }
  let name, value;
  const handleInputs = async (e) => {
    e.preventDefault();
    name = e.target.name;
    value = e.target.value;
    setuserDetails({ ...userDetails, [name]: value })
    userDetailsValue = { ...userDetails, [name]: value };
    console.log(userDetailsValue);
  }

  const handleSubmit = async () => {
    userDetailsValue = { ...userDetails, [name]: value };
    console.log(userDetailsValue);
  }
  const handleName = async (e) => {
    e.preventDefault();
    name = e.target.name
    value = e.target.value;
    setCompanyName({ ...companyName, [name]: value })
  }


  return (
    <div className="absolute w-full text-center ">
      <Head>
        <title>DDW ADD&apos;s</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="  h-screen items-center flex justify-center ">
        <form className="bg-white flex rounded-lg w-3/5 mt-16 font-latoRegular">
          <div className="flex-1 text-gray-700  p-20 text-center mt-2 ">
            <h1 className="text-3xl pb-2 font-latoBold " >
              DDW ADD&apos;s
            </h1>

            <div className="mt-6  ">
              {/* Name input field */}
              <div className="flex flex-col">
                <label className="uppercase text-sm py-2">Company Name</label>
                <input
                  className="border-2 rounded-lg p-2 flex border-gray-300"
                  name="company name"
                  type="text" placeholder="Enter Company Name"
                  onChange={handleName}
                />
              </div>
              <div className="flex flex-col">
                <label htmlFor="" style={{ marginTop: "1px" }} >
                  Interest :
                </label>
                <div className="text-center">

                  <Dropdown onSelect={onSelect} />
                </div>
              </div>

              <div className="flex flex-col">
                <label className="uppercase text-sm py-2">
                  Counter
                </label>
                <input
                  className="border-2 rounded-lg p-2 flex border-gray-300"
                  type="number" placeholder="count"
                  onChange={handleInputs}
                />
              </div>

              <div className="flex flex-col">
                <label className="uppercase text-sm py-2">
                  Check Price
                </label>
                <input
                  className="border-2 rounded-lg p-2 flex border-gray-300"
                  name="check price"
                  type="number" placeholder="check the price"
                  onChange={handleInputs}
                />
              </div>
              <div className="grid grid-cols-1  w-full">
              <div>
                  <button
                    type="submit"
                    className=" bg-gradient-to-r from-rose-400 via-fuchsia-500 to-indigo-500 p-2 font-latoBold text-sm text-white py-3 mt-6 rounded-full w-3/5"
                    onClick={handleSubmit}
                  >
                    
                    Submit

                  </button>
              </div>
              <div>
              <Link href="/new">
                    <button
                      type="submit"
                      className="bg-gradient-to-r from-rose-400 via-fuchsia-500 to-indigo-500 font-latoBold text-sm text-white py-3 mt-6 rounded-full w-3/5"
                   
                    >
                      Proced to next
                    </button>
              </Link>
                 
              </div>
               
                
              </div>
            </div>
          </div>
        </form>


      </div>

    </div>
  );
}
